Updated RNN
DeepTrackAI/deeplay pull request #58
Opened 2024-01-09 09:57 UTC by Henrik-KM

Moved RNN to Applications, added RecurrentBlock. RNN blocks are no longer nested.

2024-01-09 12:25 UTC, cmanzo commented
It looks good, I tried it with the AnDi example.
I was wondering whether the application `rnn` should be called something like `RecurrentNeuralNetworkwithDenseTop` or `RecurrentNeuralNetworkforClassification` @giovannivolpe @BenjaminMidtvedt what do you think?

2024-01-11 16:02 UTC, BenjaminMidtvedt commented
Since it's an application, maybe `RecurrentClassifier` or `SequenceClassifier`

2024-01-11 16:07 UTC, BenjaminMidtvedt requested changes

2024-01-11 16:07 UTC, BenjaminMidtvedt commented on deeplay/applications/timeseries/rnn.py
> +class rnn(DeeplayModule):
Agree with Carlo, maybe `RecurrentClassifier` or `SequenceClassifier` or `SeriesClassifier`. Try to keep the names as agent nouns

2024-01-30 13:23 UTC, merged